# Generated by Django 5.1.6 on 2026-08-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('sex', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin'), ('O', 'Autre / inconnu')], default='O', max_length=1, verbose_name='sexe')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name='lieu de naissance')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='date de décès')),
                ('death_place', models.CharField(blank=True, max_length=200, verbose_name='lieu de décès')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'personne',
                'verbose_name_plural': 'personnes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_type', models.CharField(choices=[('marriage', 'Mariage'), ('pacs', 'PACS'), ('cohabitation', 'Union libre'), ('other', 'Autre')], default='marriage', max_length=20, verbose_name="type d'union")),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions_as_person1', to='genealogy.person', verbose_name='personne 1')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions_as_person2', to='genealogy.person', verbose_name='personne 2')),
            ],
            options={
                'verbose_name': 'union',
                'verbose_name_plural': 'unions',
            },
        ),
        migrations.CreateModel(
            name='Parentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('biological', 'Biologique'), ('adoptive', 'Adoptif'), ('foster', "Famille d'accueil")], default='biological', max_length=20, verbose_name='type de filiation')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_links', to='genealogy.person', verbose_name='enfant')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to='genealogy.person', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'filiation',
                'verbose_name_plural': 'filiations',
                'constraints': [models.UniqueConstraint(fields=('parent', 'child'), name='unique_parentage')],
            },
        ),
    ]
