# Generated by Django 5.1.6 on 2026-08-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_home_person',
            field=models.BooleanField(default=False, help_text="Personne dont l'arbre s'affiche sur la page d'accueil (une seule à la fois).", verbose_name='personne de référence'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('is_home_person', True)), fields=('is_home_person',), name='unique_home_person'),
        ),
    ]
