# Generated by Django 5.1.6 on 2026-08-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_person_is_home_person_person_unique_home_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('birth', 'Naissance'), ('baptism', 'Baptême'), ('death', 'Décès'), ('burial', 'Inhumation'), ('marriage', 'Mariage'), ('divorce', 'Divorce'), ('residence', 'Résidence'), ('census', 'Recensement'), ('occupation', 'Profession'), ('education', 'Éducation'), ('other', 'Autre')], default='other', max_length=20, verbose_name="type d'événement")),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='intitulé')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date (pour le tri)')),
                ('date_text', models.CharField(blank=True, max_length=120, verbose_name='date affichée')),
                ('place', models.CharField(blank=True, max_length=300, verbose_name='lieu')),
                ('description', models.TextField(blank=True, verbose_name='détail')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.person', verbose_name='personne')),
                ('related_person', models.ForeignKey(blank=True, help_text='Le conjoint pour un mariage, par exemple.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_related', to='genealogy.person', verbose_name='personne associée')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['person', 'date'], name='genealogy_e_person__4f8518_idx')],
            },
        ),
    ]
